"""Add runtimes table

Revision ID: 048563118652
Revises: 
Create Date: 2026-08-04 10:06:36.683835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048563118652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('editor_name', sa.String(length=100), nullable=False),
    sa.Column('editor_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ENABLED', 'DISABLED')", name='check_valid_status'),
    sa.ForeignKeyConstraint(['added_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtimes')
    # ### end Alembic commands ###
