"""Added Job model

Revision ID: d8c01e4117a0
Revises: e6ee6da462ec
Create Date: 2026-09-20 19:24:24.202358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c01e4117a0'
down_revision = 'e6ee6da462ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('project_id', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_job_id', sa.String(length=150), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('script', sa.String(length=500), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('runtime_id', sa.String(length=500), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('ram', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
